### ISSUE TITLE
[WIP] EPIC: Prototype workflow for transcriptioning and captioning

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss-labs/sul_media_transcription_tools#1]
Some admonishments/guidelines for the below work, based on 2024-09-10 planning meeting:
- We are assuming that we will use Whisper, or some variant (e.g. WhisperX), because it provided what we felt was the best combination of output quality and performance from the tools that were evaluated earlier in 2024 (@edsu may be able to link to that analysis for context?).  If we determine that we want to go with a completely different model, we need to write up our reasoning for approval.
- We want our solution to provide access to Whisper's tuning parameters so that we can tweak them as needed, so completely blackbox solutions that run Whisper with no access to configuration aren't acceptable.
- We would like to avoid (or at least minimize as much as possible) vendor lock-in.  We're highly likely to go with AWS to start, since we have more departmental expertise there, but GCP isn't out of the question.  The cloud vendor has to be an org with which Stanford has a business agreement, and which is available through Cardinal Cloud, so that might rule out anything other than Amazon and Google?
  - But as much as possible, we should use building blocks that have analogs in multiple major cloud vendors, and we should define and deploy our infrastructure using Terraform, since it's meant to be platform agnostic and the department already uses it.

- [ ] Investigate running open source Whisper in a container that we define and for which we manage deployment
  - [ ] provision S3 buckets and credentials for temp space to hold 1) the incoming content to be transcribed/captioned, and 2) the generated transcript/caption files.
  - [ ] Define a Docker container for running Whisper (lives in this repo?)
    - If docker entry point is something that gets some args and runs and exits, container disappears on its own?
    - dlme-transform traject example: https://github.com/sul-dlss/dlme-transform/blob/main/Dockerfile
    - Setting the entry point to an invocation script can indeed control how it runs, so e.g. invocation script takes params (not exactly sure how to pass to ECS task, but probably env vars?)
    - Whisper is designed to run this way from CLI, so should be a good fit for this approach? (also usable as a library, but primarily for CLI)
  - [ ] Questions surrounding the container itself
    - [ ] What runs the container?  Most likely possibility at first glance seems like AWS ECS (Elastic Container Service, for auto-scaling container based services on demand)?  Another option might be to spin up and manage AWS EC2 instances more directly.  Would this provide any advantage over ECS, given that it's likely more development and management work?  Is it more platform agnostic (i.e. does ECS have a GCP counterpart?).
    - [ ] How do we trigger the containerized Whisper to run on some content?  A REST call to a transcription API that sits in front of the container instances doing the work?  Something that watches the S3 bucket for new content, a la what we had abbyy_watcher do for detecting content to OCR?
    - [ ] How do we scale/limit the number of containers running at once?  This question would seem to nudge us towards ECS or similar.
